### PR TITLE
c64 screencode (POKE) codecs

### PR DESCRIPTION
**Pull request by irmen**
- added uppercase and lowercase c64 screencode (POKE) codecs (for all non-reversevideo characters 0-127)
- small unittest added
- small tool added to (re)create the codec python source code from the tables.

### CODE REVIEW

**Comment by irmen** [comment]
@dj51d will you be considering this pull request as well? to add the screencode ('POKE') variants of the codecs

**Comment by dj51d** [comment]
Sorry for the delinquent reply to the PR, I haven't had much time for personal projects lately.  I should have a chance to review the PR later this week

**Review by dj51d — APPROVED** [review]
Thanks for the contribution, sorry I was so delinquent in reviewing and approving it.

**Comment by irmen** [comment]
@dj51d no worries, thanks for merging the PR!   I am using the library in a hobby project that is going to be some sort of cross compiler for an experimental language to the C-64/6502 CPU.  Also, I would like to use it in my Python C-64 "emulator"  https://github.com/irmen/pyc64   But to do that properly a new 0.2.0 Pypi release would be awesome. Will you do this as well?

**Comment by dj51d** [comment]
Version 0.2.0 has now been released both here on github and on [pypi](https://pypi.org/project/cbmcodecs/)

**Comment by irmen** [comment]
much appreciated!

**Pull request merged**
