### PR TITLE
Fix for horizontal line code point and several box symbols

### PR DESCRIPTION
**Pull request by irmen**
This fixes the incorrect BOX DRAWINGS LIGHT HORIZONTAL code point as mentioned in issue #1

### CODE REVIEW

**Comment by irmen** [comment]
@dj51d are you still working on this?

I'm busy enhancing this library in my fork with this bugfix, and am now adding codecs for the c64 screen code (POKE) translations as well.

**Comment by irmen** [comment]
Also uses several unicode block symbols instead of placeholders, fixes issue #3

**Review by dj51d — APPROVED** [review]
@irmen thanks for the contribution.  I will get the new version uploaded to PyPI in the next couple of days.

**Comment by irmen** [comment]
@dj51d thanks for accepting!

Are you interested in my other enhancements as well?   I've added a screencode (POKE) mapping and codec as well, and added some unit tests.   You can have a look at my fork's master branch to see it.

**Pull request merged**
